### ISSUE TITLE
公式パンフレット作成

### ISSUE THREAD

**Issue by ghost** [gishohaku/staffs-1#11]
# 概要

公式パンフレットを作成する。

1. 運営情報などの記事
2. 公式サイト/アプリ等の記事
3. スポンサー記事（各社4ページ以内）＋スポンサー広告（各社1ページ）
4. サークルリスト

**Comment by ghost** [comment]
@mottox2 公式サイトやアプリ等の内容をもとに公式パンフレットに記載するようなネタってありますか？ページ数はそんなに多くなくても大丈夫です。

**Comment by ghost** [comment]
@mottox2 さんの記事確定

**Comment by ghost** [comment]
追加で、サークルのアピールページを作ってもらうのを検討する @oyakata2438

**Comment by oyakata2438** [comment]
カタログ関係検討
・表紙イラスト？
・印刷部数
・タイトル

中身
・開催挨拶、コンセプト
・配置図
・サークルカット
・技書博を支える技術
・サークルコラム
　（サークル概要、本の紹介、コミュニティ活動等、なんでも良い。1ページ×70サークル）
・スポンサー記事、スポンサー広告

費用感
栄光　B5　1000部として、
100P　276500→193550
152P　394000→275800
（サンバセット（定価）ここから、公式パンフ3割引として、右の費用。

無料配布はちょっと厳しい？

**Comment by oyakata2438** [comment]
技書博サークルコラム(告知文)

1サークル1ページで、あなたのサークル、本の紹介をいただけませんか？
テキストでも、画像でも、なんでも結構です。あふれるパッションを存分に発揮してください。

掲載情報の例
・著者自己紹介・サークル紹介
・本の概要、表紙等
・これまでのサークル活動紹介
・本を書くに至った経緯、モチベーション
・本で取り上げた技術の紹介記事・コラム
・電子版・通販へのリンク（Booth、とらのあな等)
　など。内容は自由です。

原稿料　なし(投稿料・掲載料もなし)
予定印刷部数　1000冊。サークル参加者、一般参加者に配布予定。

募集要項：
体裁:B5(原寸)　下余白を15㎜確保ください。(ノンブル用)
グレースケール(カラー原稿の場合、編集部でグレースケール変換します)
締め切り:6月30日23:59
提出方法:技書博公式メール（メアド入れる)にpdfを送付。
　メールタイトルは、「サークル名-サークル紹介原稿」でお願いします。
注意事項：
　・成人向け内容はNGです。
　・他者の権利を侵害しないようご注意ください。
　・締め切り厳守でお願いします。(編集の都合もあり、遅れ救済は困難です)
＝＝＝＝＝


・・・自由といいつつ、何かフォーマット作ったほうがいいかなあ…
Word？
ReViewだと編集が大変だし、使えない人のケアが大変…完成原稿pdfで上げてほしいのと、
Reviewは隙間が多いので今一つ・・・

**Comment by ghost** [comment]
> ・表紙イラスト？

表紙はデザインスポンサーに作ってもらいます。

> ・印刷部数

1000部、または、1200部（※各ノベルティのセット数にあわせる）

> ・タイトル

「技術書同人誌博覧会 公式ガイドブック」的な感じですね。
候補あったら出してください

> 無料配布はちょっと厳しい？

基本的には無料配布にしたいです。
スポンサー（10万円*2社）から費用を捻出する計画。
頑張って20万以下を死守してほしい！

**Comment by ghost** [comment]
入稿完了してるのでクローズします
