### ISSUE TITLE
ごみ出しの確認

### ISSUE THREAD

**Issue by ghost** [gishohaku/staffs-1#20]
# 概要
当日大量のごみが出ることが予想されるので、処理方法を確認する。

## 可燃/不燃などの袋に入るごみ
会場調整 #7 にあるとおり、会場より提供されるゴミ袋によって捨てることができる。
※枚数を事前確定する必要があるか要確認

## 段ボール
会場に確認する必要がある。

**Comment by ghost** [comment]
利用案内P12に記載。

- 可燃/不燃/資源ゴミ … 45L 300円 / 70L 500円
- 紙ごみ … 20kg 300円 / 30kg 500円
- 段ボール … 10kg 300円 / 15kg 500円

※これらは当日購入でOK

**Comment by ghost** [comment]
余裕をもってざっくり3万円位予算に積んでおけばよさそう

**Comment by oyakata2438** [comment]
サークル参加者には、少し前に(サークル参加要領告知くらいのタイミングで)
ゴミは現地処理可能、を告知してほしい。
技術書典はゴミ捨てNGなので、その流れでゴミ持ち帰り？と思うサークルもいる可能性あり。
