### ISSUE TITLE
スタッフ事前説明会

### ISSUE THREAD

**Issue by ghost** [gishohaku/staffs-1#22]
# 概要

当日スタッフ向けの事前説明会を開催する。

## 今後のタスク

- [ ] 事前説明会の開催場所を選定する
- [ ] 当日スタッフ用しおり #5 を作成する
- [ ] 当日スタッフに案内する
- [ ] 事前説明会を実施する

**Comment by nano-nano** [comment]
思いつきのメモです。
開催時期的には当日の２週間前あたりが３連休なので、その辺がよさそうな気がします。
場所は人数次第ですが、レンタルスペースとかそんなレベルでいいと思います。
（机と椅子があって、資料をプロジェクタで投影orホワイトボードに掲示できればよいですね）

**Comment by ghost** [comment]
早すぎる気がしますー。通常カンファレンスだと結構ギリギリにやってるイメージが強いですし、平日夜の方が集まりやすくないですか？日程は基本お任せしますので、休日にやる必要があるか十分検討して決めてください！
日程は募集開始前に決めちゃいましょう！

**Comment by nano-nano** [comment]
> 通常カンファレンスだと結構ギリギリにやってるイメージが強いですし、平日夜の方が集まりやすくないですか？

確かに平日夜の方が参加しやすいかもですね
開催週～その1週前あたりで、19:30から1.0～1.5h程度でいけるかな
どのくらいの人が当日スタッフに手を挙げてくれるかなー

**Comment by ghost** [comment]
> どのくらいの人が当日スタッフに手を挙げてくれるかなー

役割から目標人数決めないとですね。
早めに募集すれば、20人ほどは集まると想像してます。

**Comment by nano-nano** [comment]
事前説明会のAgendaとかのメモ...
https://hackmd.io/@-xLxkrFSSF6l8bKPntEnZg/H1RTuzT04
