### ISSUE TITLE
会場ネットワーク使用

### ISSUE THREAD

**Issue by ghost** [gishohaku/staffs-1#23]
# 概要
当日会場のネットワーク一般開放について検討する。

## 会場にある無線機器
BUFFALO WAPM-APG600H
https://www.buffalo.jp/product/detail/wapm-apg600h.html
※SSID+Passで接続する（一般開放可）

**Comment by ghost** [comment]
全体予算を早めに検討したいので、5月中にざっくり候補欲しいです。一般来場者は費用高いならなしで大丈夫ですが、希望サークルには提供可能なレベルにしたいですね。 @natsuo-git

**Comment by 773kai** [comment]
だいたい返事がどの企業もこんな感じで悩ましいところ。

スケジュールを確認いたしましたところ、イベント開催時期、
7月27日（土）に大きなイベントが多数重なっており、
誠に申し訳ございませんが、対応いたしかねる状況でございます。

予算的にしんどそうなので、希望サークル＆運営更新用のみで着地させたい。
CoreスタッフもわざわざWi-Fi使うこともそんなにないと思っている。

その為Issueとしては終了としたい。
@ariakira

**Comment by ghost** [comment]
@natsuo-git ありがとうございました。今回は見送りでいきましょう。
また、会場から提供されるWi-Fiは速度保証せず譲り合いながら使うという感じにしましょう。
