### ISSUE TITLE
未入金サークル対応

### ISSUE THREAD

**Issue by TakumaNakagame** [gishohaku/staffs-1#34]
あるサークルのみ、入金確認が取れていない。
メールにて連絡を行っているが、レスポンスが無いので @ariakira によりTwitterのDMを送信。

6/4までに連絡が無いようであればReject対応をする。

### 期限

__06/04 23:59__

**Comment by ghost** [comment]
6/3 14:55時点で先方から返信なし。ここ数日Twitter更新がないため、気づいていないかもしれない。

**Comment by ghost** [comment]
対象者にお断りいれましたのでクローズします
