### ISSUE TITLE
当日スタッフ募集

### ISSUE THREAD

**Issue by ghost** [gishohaku/staffs-1#4]
# 概要

当日スタッフの設計及び募集を行う。

### 募集開始前のタスク

- [ ] 当日スタッフへの説明会を準備する
    - 当日スタッフ募集時に日時を告知できるよう優先して対応すること
    - 説明会の会場手配及び日程調整
- [ ] 公式サイト上で募集を告知する
- [ ] 公式Twitter上で募集を告知・拡散する

### 募集開始後のタスク

- [ ] 当日スタッフに対応していただく作業と目標人数を確定する
- [ ] 当日スタッフの配置を確定する
- [ ] 当日スタッフ向けのドキュメント（スタッフのしおり）を作成する
- [ ] 当日スタッフをSlackワークスペースに招待する
- [ ] 当日スタッフ用チャンネルを作成してジョインしてもらう
- [ ] 事前説明会の案内としおりの掲示

**Comment by nano-nano** [comment]
> 説明会の会場手配及び日程調整

#22 で少し話をしたところではありますが、開催日はあまり早くなくて良いとのことでしたので
- 日程: 開催週（22日〜26日）かその前週（16日〜19日）　世間的に定時退社日が多い水曜日あたり？
- 開始時刻: 19:30開始
- 所要時間: 1.0〜1.5h

で開催できればと。
いわゆる会議スペース等を確保したことないので、使いやすそうな場所があれば提案頂きたいです。

**Comment by nano-nano** [comment]
>　所要時間: 1.0〜1.5h

もっと短くてもいいかも……？
余った時間はコアスタッフの打ち合わせに使ってもよいですね。

**Comment by nano-nano** [comment]
> 開始時刻: 19:30開始

これも早いですかね。所要時間が短くできれば20:00開始でもよさそうです。

**Comment by nano-nano** [comment]
当日スタッフ募集フォームの内容も見始めました。
確認しておきたい事項は次の通りです。

- 名前/名前カナ
  - 本名以外も許容する？（本名を書きたがらない人もいそう。用途にもよります）
  - 名前の使用用途をはっきりさせたい（スタッフ名札用？スタッフ保険用？一時的な連絡用？）
- 緊急連絡先
  - 書いてほしいのは電話orメール？（緊急時対応という意味では電話？）
- 備考（←追加しました）
  - 活動時間に制約があるとか、当日活動するにあたって配慮してほしいことなど、運営事務局に伝えておきたい事柄を書いてもらうことが意図。説明文の内容は要検討。

**Comment by ghost** [comment]
> 名前/名前カナ
> 本名以外も許容する？（本名を書きたがらない人もいそう。用途にもよります）
> 名前の使用用途をはっきりさせたい（スタッフ名札用？スタッフ保険用？一時的な連絡用？）

保険用なので、表示名と本名両方が必要です！

> 緊急連絡先
> 書いてほしいのは電話orメール？（緊急時対応という意味では電話？）

メールアドレスはフォーム機能で別途取得するので電話番号です。
※なしでも問題ない気がします。

**Comment by ghost** [comment]
1.5hで終了するなら、20:00開始、21:30終了でよいかと思います。
人数規模によって場所検討しますので、まずは募集を先にしましょうか。
ある程度見込みがついたところで会場探します。

**Comment by nano-nano** [comment]
当日スタッフ募集フォームの内容を更新しました。
残件は次の通りです。

- スタッフ用Slackスペース招待の締切（フォーム締切＋1週間くらいでどうでしょう？）
- 事前説明会の日程を書くかどうか（「7月第4週」のような幅のある表記もひとつの方法）
- 懇親会の時間をどう書くか（ #1 での議論次第ですが...）
- フォームの締切をいつにするか（6月30日でどうでしょう？）
- 公開用の名前は任意で問題ないか（一応、掲載されたくない人のことも配慮はしたい。掲載先は公式サイトとパンフくらいでしょうか？）
- 前日準備の規模（1〜2時間程度としておきましたが、作業内容次第ですね）
- 備考欄の説明に載せておく例（「家が遠いので、集合時間に遅れるかも」とか、他にありますでしょうか？）

**Comment by nano-nano** [comment]
> 公式サイト上で募集を告知する

告知ページの内容も考えないといけないですね

```
技書博では、当日運営をお手伝い頂ける当日スタッフを募集しています。
当日スタッフとしてお手伝い頂く内容は「当日来場する一般参加者やサークル参加者への応対」
「技書博の円滑な運営のための会場内外の安全確保」等を想定しています。
当日スタッフとしてお手伝い頂いた方には、お礼として〜〜〜
（↑なにかお礼や特典のようなものがあれば）

当日スタッフとしてお手伝い頂ける意志をお持ちで、次の条件を満たす方は
こちら（←リンク）のスタッフ募集フォームに必要事項を記入して送信してください。
折り返し、スタッフ用Slackへの招待メールを送らせていただきます。

【当日スタッフの条件】
- 義務教育を終了していること
- 未成年の場合、保護者・家族の承諾を得ていること
- ...
（↑条件をみんなで考えましょう）

募集の締切は、6月30日23:59です。
```

こんな感じですかね？

**Comment by ghost** [comment]
> （↑なにかお礼や特典のようなものがあれば）

特典つけるの難しいですねー。
事務局からは特になしでもよいように思います。

> （↑条件をみんなで考えましょう）

「コミュニティガイドラインを遵守頂ける方」があればよいです！
https://portal.engineers-lt.info/guideline/

**Comment by nano-nano** [comment]
> 特典つけるの難しいですねー。
> 事務局からは特になしでもよいように思います。

それでは、ここは特に触れずに削っちゃいましょう。

> 「コミュニティガイドラインを遵守頂ける方」があればよいです！

他は特に大丈夫でしょうか？
活動時間（最低でもn時間は活動できること）とか、そういうものがあれば挙げておきたいです。

それと、告知ページのDraftはGoogleドライブ上で管理するのが良さそうですかね？
（たぶん何度か推敲するので...）

**Comment by ghost** [comment]
> 他は特に大丈夫でしょうか？
> 活動時間（最低でもn時間は活動できること）とか、そういうものがあれば挙げておきたいです。

活動時間としては「当日参加できる方」でよいかと思います。
基本的には1日のうちで3～4時間程度シフトくんで作業してもらうイメージで、どうしても外したい時間は事前申告のうえ調整でしょうか。
カンファレンスではないのでそんなに要望はなさそう。

> それと、告知ページのDraftはGoogleドライブ上で管理するのが良さそうですかね？
原稿Markdownなので何でも大丈夫です！
カジュアルに編集するならhackmdとかでもいいですね

**Comment by nano-nano** [comment]
> カジュアルに編集するならhackmdとかでもいいですね

作ってみました！
https://hackmd.io/s/H1CG9JdpE
スタッフ条件は最低限にして（さすがに義務教育終了前の人が来ることはないだろう……）シンプルにしました。
必要事項はフォームで聞いていますからね。

**Comment by ghost** [comment]
文言いくつか追加しました！（一応年齢かいときました） @nano-nano
