### ISSUE TITLE
当日スタッフ用しおり作成

### ISSUE THREAD

**Issue by ghost** [gishohaku/staffs-1#5]
# 概要

当日スタッフ #4 が行う作業をドキュメント化する。
[しおりのサンプルはこちら](https://docs.google.com/presentation/d/1O3BhYvLGwIdlGom2vYSawlSX4LxOu1OggDVYNpDr1fk/edit?usp=sharing)（@ariakiraが過去作成したもの）

## 今後のタスク

- [ ] 役割及び希望人数を確定する
    - 各コアスタッフへのヒアリングをしてください
- [ ] 役割ごとの作業内容を確定し、ドキュメント化する
- [ ] 応募者から役割を割り振る

**Comment by nano-nano** [comment]
> 役割及び希望人数を確定する

の点、同人即売会スタッフ経験からどんな役割があるのかをざっくり挙げてみます。
（上に書いているものほど優先順位が高いと考えて頂いてOKです）

- 総本部
  - 主催者を中心に、イベント全体の進行に関わる調整・意志決定を行います
  - 対外的な対応（会場側や警察消防などとの調整など）も、最終的には総本部対応になります
  - イベント内向けには会場アナウンスなどの全体へのお知らせ業務や事務仕事もあります

- 場内（館内）担当
  - 会場内でイベントが安全かつ円滑に進むよう、実務一般を行います
  - 具体的には、会場内の混雑対応（混雑サークル列対応や動線確保）や問い合わせ対応、巡回業務などがあります
  - カタログを入場チケット代わりにする場合のチェックや、サークルからの見本誌回収なども、一般的には場内担当の業務として扱われることが多いです

- 場外（警備）担当
  - イベント会場外における安全確保等の実務一般を行います
  - 具体的には、待機列の形成・管理、入場誘導、参加者の問い合わせ対応などがあります
  - イベントに関係ない人（参加者と区別して「一般来場者」と言うこともあります）から直接問い合わせを受けることもあり得ます

だいたいここまでが必須といえる役割ですね。
その他にも、

- 販売担当
  - 公式販売物（ノベルティやカタログなど）の販売全般を行います
  - 現金を取り扱うという観点からは責任重大です
  - 規模が大きくなければ総本部業務の一部として対応しても良いと思います

- スポンサー担当
  - 当日業務において、総本部とスポンサーとの間を取り持ちます
  - これも、スポンサーブースの規模が大きくなければ総本部業務の一部として対応しても良いと思います

などが挙げられます。
それ以外は各イベントごとに特殊な担当があったりなかったりするものなので、イベントの企画次第です。
（ 余談ですが、私は場外担当系の業務経験が一番長いです）

**Comment by ghost** [comment]
@nano-nano コメントありがとうございます。

場内外担当ですが、今回警備スタッフの雇用も併せて検討しています。
警備会社の見積もりをとっている段階なので、進捗は #10 で都度共有しますね。
総本部業務など細かなことは今後議論させてください。

> 販売担当

こちらは公式グッズは販売しない（頒布はすべて無料）を計画しています。
懇親会含めスタッフ外から金銭を直接預かる業務は発生しない想定です。

> スポンサー担当

こちらは @yamashirotakashi と @ariakira で担当します！

**Comment by nano-nano** [comment]
> 場内外担当ですが、今回警備スタッフの雇用も併せて検討しています。

了解です！そちらも見つつ業務分掌ができるようにしますね。
#27 で一般参加者の入場は時差入場の方針とのことですから、展示室入口付近で人がワサっと列になる可能性は低そうですが、それでも待ち行列は多少出来そうな気もするので、そこは計画時に留意ですね。

> こちらは公式グッズは販売しない（頒布はすべて無料）を計画しています。
> 懇親会含めスタッフ外から金銭を直接預かる業務は発生しない想定です。

良いと思います。金銭が関わるといろいろ手間になるので。
グッズの渡し方は気にした方がよいかもですね（入場の流れでやるのか、机を出して置いておくのか、etc.）

一応上に挙げたのはよくあるタイプの役割なので、あとは技書博の企画に合わせて役割を切っていけるといいかな。

**Comment by ghost** [comment]
入場時間については別 #27 で議論しましょう！
入場方法ですが、いまのところ、QRコード読んで受付して名札とトートバッグを渡す、手荷物検査をするくらいのイメージです。
